repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.407
    hooks:
      - id: pyright
        exclude: ^core/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
        args: [ --fix ]
        exclude: ^core/|manage.py|user/migrations
      - id: ruff-format